# Generated by Django 5.2.1 on 2025-06-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_allowed_roles_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_type',
            field=models.CharField(choices=[('positive', 'Comentario Positivo'), ('suggestion', 'Sugerencia de Mejora'), ('problem', 'Reporte de Problema'), ('neutral', 'Comentario General')], default='neutral', help_text='Tipo de comentario para categorización', max_length=20),
        ),
    ]
