# Generated by Django 5.2.1 on 2025-06-06 05:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_review_comment_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={},
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                help_text="Sala reservada",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="rooms.room",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("confirmed", "Confirmada"),
                    ("in_progress", "En Progreso"),
                    ("completed", "Completada"),
                    ("cancelled", "Cancelada"),
                ],
                default="confirmed",
                help_text="Estado actual de la reserva",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                help_text="Usuario que realiza la reserva",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="cleanliness_rating",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Calificación de limpieza de 1 a 5 estrellas",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comfort_rating",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Calificación de comodidad de 1 a 5 estrellas",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comentario adicional sobre la experiencia"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="equipment_rating",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Calificación de equipamiento de 1 a 5 estrellas",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reservation",
            field=models.OneToOneField(
                help_text="Reserva asociada a esta reseña",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="rooms.reservation",
            ),
        ),
    ]
