# Generated by Django 5.2.1 on 2025-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_options_alter_reservation_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('aula', 'Aula'), ('laboratorio_ciencias', 'Laboratorio de Ciencias'), ('laboratorio_informatica', 'Laboratorio de Informática'), ('biblioteca', 'Biblioteca'), ('sala_profesores', 'Sala de Profesores'), ('auditorio', 'Auditorio'), ('equipamiento', 'Equipamiento/Recurso'), ('sala_reunion', 'Sala de Reuniones')], default='aula', help_text='Tipo de sala', max_length=30),
        ),
    ]
