# Generated by Django 5.2.1 on 2025-06-16 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSecurityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('admin', 'Administrador'), ('soporte', 'Soporte Técnico'), ('default', 'Por Defecto')], help_text='Rol de usuario al que aplica esta regla', max_length=20, unique=True)),
                ('max_reservations_per_hour', models.PositiveIntegerField(default=3, help_text='Máximo número de reservas por hora')),
                ('max_reservations_per_day', models.PositiveIntegerField(default=10, help_text='Máximo número de reservas por día')),
                ('max_reservations_per_week', models.PositiveIntegerField(default=20, help_text='Máximo número de reservas por semana')),
                ('max_total_hours_per_day', models.PositiveIntegerField(default=8, help_text='Máximo total de horas reservadas por día')),
                ('max_total_hours_per_week', models.PositiveIntegerField(default=30, help_text='Máximo total de horas reservadas por semana')),
                ('max_concurrent_reservations', models.PositiveIntegerField(default=3, help_text='Máximo número de reservas activas simultáneamente')),
                ('max_advance_days', models.PositiveIntegerField(default=30, help_text='Máximo días de anticipación para reservar')),
                ('enable_pattern_detection', models.BooleanField(default=True, help_text='Habilitar detección de patrones abusivos')),
                ('block_duration_minutes', models.PositiveIntegerField(default=60, help_text='Duración del bloqueo temporal en minutos cuando se detecta abuso')),
                ('warning_threshold', models.FloatField(default=0.8, help_text='Umbral de advertencia (porcentaje del límite) para notificar al usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de Seguridad de Reserva',
                'verbose_name_plural': 'Reglas de Seguridad de Reservas',
            },
        ),
        migrations.CreateModel(
            name='ReservationUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Crear Reserva'), ('cancel', 'Cancelar Reserva'), ('attempt_blocked', 'Intento Bloqueado'), ('warning_sent', 'Advertencia Enviada'), ('user_blocked', 'Usuario Bloqueado')], max_length=20)),
                ('reservation_id', models.PositiveIntegerField(blank=True, help_text='ID de la reserva relacionada (si aplica)', null=True)),
                ('room_name', models.CharField(help_text='Nombre de la sala', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Uso de Reservas',
                'verbose_name_plural': 'Logs de Uso de Reservas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
