# Generated by Django 5.2.1 on 2025-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_terms_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante'), ('soporte', 'Soporte Técnico')], default='estudiante', help_text='Rol del usuario en el sistema', max_length=10),
        ),
    ]
