# Generated by Django 5.2.1 on 2025-06-03 13:37

from django.db import migrations


def fix_user_roles(apps, schema_editor):
    """
    Migrar usuarios con rol 'basic' a 'estudiante' y asegurar que no sean staff.
    """
    CustomUser = apps.get_model('usuarios', 'CustomUser')
    
    # Encontrar usuarios con rol 'basic' y cambiarlos a 'estudiante'
    users_with_basic_role = CustomUser.objects.filter(role='basic')
    count = users_with_basic_role.count()
    
    if count > 0:
        # Actualizar usuarios con rol basic
        for user in users_with_basic_role:
            user.role = 'estudiante'
            user.is_staff = False  # Asegurar que no sea staff
            user.is_superuser = False  # Asegurar que no sea superuser
            user.save(update_fields=['role', 'is_staff', 'is_superuser'])
        
        print(f"Migración completada: {count} usuarios cambiados de 'basic' a 'estudiante'")
    else:
        print("No se encontraron usuarios con rol 'basic' para migrar")


def reverse_fix_user_roles(apps, schema_editor):
    """
    Función reversa (no implementada ya que no queremos volver al rol 'basic').
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.RunPython(fix_user_roles, reverse_fix_user_roles),
    ]
