# Generated by Django 5.2.1 on 2025-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allowed_roles',
            field=models.CharField(default='admin,profesor,estudiante', help_text='Roles permitidos para reservar esta sala (separados por comas)', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('aula', 'Aula'), ('sala_estudio', 'Sala de Estudio'), ('sala_individual', 'Sala Individual'), ('sala_reunion', 'Sala de Reuniones'), ('laboratorio', 'Laboratorio'), ('auditorio', 'Auditorio')], default='sala_estudio', help_text='Tipo de sala', max_length=20),
        ),
    ]
